---
abstract: 'HTTP 1.1 Range-based Pagination for Dancer apps.'
author:
  - 'Colin Ewen <colin@draecas.com>'
build_requires:
  JSON: 0
  Test::More: 0
  YAML: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Paginate
no_index:
  directory:
    - t
    - inc
requires:
  Dancer: 0
  perl: 5.006
version: v1.0.2
